## generate topic labels

## generate a dict with 62 topic labels, with keys 1-62 and assign a different category to each topic
topic_labels = {0: "Episodisches Framing",
                1: "Historischer Kontext",
                2: "Unionsstreit 1",
                3: "Bürgerkrieg in Syrien",
                4: "Arbeitsmarkt",
                5: "Finanzierung der Migration",
                6: "Flüchtlingsunterbringung in Hamburg",
                7: "Humanitäre Katastrophe im Mittelmeer",
                8: "Bundesamt für Migration und Flüchtlinge (BAMF)",
                9: "Trump, Mexico, Migration",
                10: "EU Verteilung Flüchtlinge",
                11: "Abschiebung 1",
                12: "Unionsstreit 2",
                13: "Aktienkurse - Dow Jones",
                14: "Aktienkurse - DAX",
                15: "AfD Topic",
                16: "Lage in Griechenland (Ankunft & Lager)",
                17: "EU-Türkei-Deal",
                18: "Kriminalität: Gerichtsverfahren",
                19: "Flüchtlingsunterbringung in Berlin",
                20: "Brandanschläge auf Flüchtlingsheime",
                21: "Grenzkontrollen durch Polizei",
                22: "Verhandlung einer Abschiebung",
                23: "Einwanderungszahlen",
                24: "Migrationspolitik in Afrika",
                25: "Koalitionsstreit über Transitzonen",
                26: "Bundesrat Entscheidung zu sicheren Herkunftsstaate",
                27: "Einwanderung in Sozialsysteme",
                28: "Familiennachzug",
                29: "Flüchtlingsprotest am Oranienplatz in Berlin",
                30: "Abschiebung nach Afghanistan",
                31: "Seenotrettung 1",
                32: "Schulen",
                33: "Kirchen",
                34: "Balkanroute",
                35: "Jamaikasondierung",
                36: "Österreich",
                37: "Umfragen",
                38: "Fachkräftemangel",
                39: "Kriminalität: Straftaten",
                40: "Jugendliche Flüchtlinge",
                41: "Marineeinsatz gegen Schleuser im Mittelmeer",
                42: "Europäische Aktienmärkte",
                43: "Demonstrationen",
                44: "Boris Pistorius",
                45: "Jesiden",
                46: "Gesundheitsversorgung von Flüchtlingen",
                47: "Ankunft in München",
                48: "Aktien: DAX",
                49: "Grenzkontrollen Schengen",
                50: "Brexit",
                51: "Viktor Orban's Asylpolitik", 
                52: "Unterkünfte in Schleswig-Holstein",
                53: "Calais",
                54: "Doppelte Staatsbürgerschaft",
                55: "Seenotrettung 2",
                56: "Grenzkontrollen in Skandinavien",
                57: "Börse: Anleihen",
                58: "UN-Migrationspakt",
                59: "Lage an den spanischen Enklaven Ceuta und Melilla",
                60: "Schweiz",
                61: "Börse: Osteuropa"}


## write topic labels to json
import json
with open('data/processed/topic_labels.json', 'w', encoding="UTF-8") as fp:
    json.dump(topic_labels, fp)

## topic reduction

## merge topic labels
reduced_labels = {"Episodic Framing": [0],
                "Historical Context": [1],
                "Coalition Conflict": [2, 12, 25, 35],
                "Syrian Civil War": [3, 45],
                "Labor Market": [4, 38],
                "Budget for Integration": [5],
                "Housing in Germany": [6, 19, 52],
                "Humanitarian Crisis Mediterranean": [7, 31,  55],
                "BAMF": [8],
                "Trump, Mexico, Migration": [9],
                "EU Distribution of Refugees": [10],
                "Deportation": [11, 22, 30],
                "Stock Market": [13, 14, 42, 48, 57, 61],
                "AfD Topic": [15],
                "Refugee Arrival": [16],
                "EU-Turkey Deal": [17],
                "Refugee Crime": [18, 39],
                "Attacks on Refugee Homes": [20],
                "Police Action Against Human Trafficking": [21],
                "Immigration Statistics": [23],
                "Migration Policy in Africa": [24],
                "Decision on Safe Countries of Origin": [26],
                "Welfare Migration": [27],
                "Family Reunification": [28],
                "Refugee Protest Berlin": [29],
                "Refugees in Schools": [32],
                "Church Debate on Immigration": [33],
                "Balkan Route": [34],
                "Austrian Immigration Debate": [36],
                "Polls": [37],
                "Young Refugees": [40],
                "Marine Operation in Mediterranean": [41],
                "Demonstrations": [43],
                "Boris Pistorius": [44],
                "Healthcare for Refugees": [46],
                "Arrival in Munich": [47],
                "Schengen Border Control": [49, 56],
                "Brexit": [50],
                "Viktor Orban's Asylum Policy": [51],
                "Humanitarian Crisis EU Borders": [53, 59],
                "Double Citizenship": [54],
                "UN Migration Pact": [58],
                "Swiss Immigration Debate": [60]}

reduced_ids = {0: [0],
                1: [1],
                2: [2, 12, 25, 35],
                3: [3, 45],
                4: [4, 38],
                5: [5],
                6: [6, 19, 52],
                7: [7, 31,  55],
                8: [8],
                9: [9],
                10: [10],
                11: [11, 22, 30],
                12: [13, 14, 42, 48, 57, 61],
                13: [15],
                14: [16],
                15: [17],
                16: [18, 39],
                17: [20],
                18: [21],
                19: [23],
                20: [24],
                21: [26],
                22: [27],
                23: [28],
                24: [29],
                25: [32],
                26: [33],
                27: [34],
                28: [36],
                29: [37],
                30: [40],
                31: [41],
                32: [43],
                33: [44],
                34: [46],
                35: [47],
                36: [49, 56],
                37: [50],
                38: [51],
                39: [53, 59],
                40: [54],
                41: [58],
                42: [60]}


## write reduced labels to json
with open('data/processed/reduced_topic_labels.json', 'w', encoding="UTF-8") as fp:
    json.dump(reduced_labels, fp)

## write reduced ids to json
with open('data/processed/reduced_topic_ids.json', 'w', encoding="UTF-8") as fp:
    json.dump(reduced_ids, fp)
