---
title: "Frame Competition"
subtitle: "How News Framing affects Party Competition"
author: "Nicolai Berk"
institute: "Humboldt Universität Berlin"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    seal: false
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
      ratio: 16:9
    includes:
      after_body: insert-logo.html
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#004A95", background_color = "#bfbfbf",
  base_font_size = "32px",
  header_h1_font_size = "1.3rem",
  header_h2_font_size = "1.2rem",
  header_h3_font_size = "1.05rem",
  footnote_font_size = "0.75rem",
  header_font_google = google_font("Lato", '700'),
  text_font_google   = google_font("Lato", "400"),
  code_font_google   = google_font("Fira Mono")
)


```

```{r, load_refs, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE, 
           bib.style = "authoryear",
           cite.style = "authoryear",
           style = "markdown",
           hyperlink = FALSE,
           max.names = 2, 
           longnamesfirst = F,
           dashed = FALSE)
myBib <- ReadBib("C:/Users/nicol/Dropbox/Studium/BibTex/PhD.bib", check = FALSE)
```

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE, 
  message = F, 
  warning = F, 
  cache = T, 
  out.width="90%", 
  fig.height=8, 
  fig.width=15, 
  fig.align='center', 
  eval = T, 
  dev = "svg"
  )
# knitr::opts_knit$set(root.dir = 'C:/Users/nicol/Dropbox/PhD/Papers/Bild/github/bild')

library(tidyverse)
library(dplyr)
library(data.table)
library(fixest)
library(lubridate)
library(patchwork)
library(here)

# load self-made functions
for (filename in list.files(here("code/functions"))){
  source(here(paste0('code/functions/', filename)))
}


```


```{r vectors, fig.cap="Schematic representation of topic vectors for party communication and news articles.", fig.width=6, fig.height=4}

data.frame(
  item = c("News Article", "Party A", "Party B",
            "News Article", "Party A", "Party B"),
  dim1 = c(0,  0.2, 0.8,
            0,0,0),
  dim2 = c(1, 0.8, 0.2,
            0,0,0)
) %>% 
ggplot(aes(x = dim1, y = dim2, 
        color = item, linetype = item)) +
  geom_line() +
  geom_point(alpha = 0.3) + 
  theme_minimal() +
  xlab("Attention to Consideration 1") +
  ylab("Attention to Consideration 2") +
  theme(legend.title = element_blank())

```
